import type { NextPage } from "next";
import Head from "next/head";
import { Refactor } from "../components/refactor";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Age App Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/calculator-svgrepo-com.svg" />
      </Head>
      <main className="flex  min-h-screen flex-col  items-center  bg-template_off_white font-['Poppins']">
        <Refactor />
      </main>
    </>
  );
};
export default Home;
